public class TestBST {
    public static void main(String[] args) {
        BST a = new BST();
        System.out.println("isEmptyTree = " + a.isEmptyTree());
        movieNode xNode = new movieNode("Jane", 123456789, 23456789);
        movieNode yNode = new movieNode("Joe", 934567890, 34567890);
        movieNode zNode = new movieNode("Jack", 223452234, 23452234);
        movieNode kNode = new movieNode("Jill", 934567856, 34567856);
        movieNode aNode = new movieNode("Abe", 123456788, 23456788);
        movieNode bNode = new movieNode("Beth", 934567898, 34567898);
        movieNode cNode = new movieNode("Chuck", 223452238, 23452238);
        movieNode dNode = new movieNode("Dot", 934567858, 34567858);
        movieNode mNode = new movieNode("Mike", 723452237, 23452237);
        movieNode nNode = new movieNode("Nick", 734567857, 34567857);
        movieNode oNode = new movieNode("Otis", 734562222, 34562222);
        a.insert(xNode);
        a.insertID(xNode);
        a.insert(yNode);
        a.insertID(yNode);
        a.insert(zNode);
        a.insertID(zNode);
        a.insert(kNode);
        a.insertID(kNode);
        a.insert(mNode);
        a.insertID(mNode);
        a.insert(nNode);
        a.insertID(nNode);
        a.traverse();
        a.printTree();
        System.out.println("search");
        System.out.println(a.search(123456789).getTitle());
        System.out.println(a.search(934567890).getTitle());
        System.out.println(a.search(223452234).getTitle());
        System.out.println(a.search(934567856).getTitle());
        a.traverse();
        a.printTree();
        System.out.println("searchFor 7890");
        System.out.println(a.search(934567890).getTitle());
        System.out.println("delete6789");
        a.delete(xNode);
        a.deleteID(xNode);
        a.traverse();
        a.printTree();
        System.out.println("delete2237");
        a.delete(mNode);
        a.deleteID(mNode);
        a.traverse();
        a.printTree();
        System.out.println("delete7857");
        a.delete(nNode);
        a.deleteID(nNode);
        a.traverse();
        a.printTree();
        System.out.println("insert6788");
        a.insert(aNode);
        a.insertID(aNode);
        a.traverse();
        a.printTree();
        System.out.println("insert2222");
        a.insert(oNode);
        a.insertID(oNode);
        a.traverse();
        a.printTree();
        System.out.println("delete2234");
        a.delete(zNode);
        a.deleteID(zNode);
        a.traverse();
        a.printTree();
        System.out.println("isEmptyTree = " + a.isEmptyTree());
    }

}
